### ISSUE TITLE
Maybe use JSDoc/TSDoc?

### ISSUE THREAD

**Issue by Bikossor** [microsoft/ts-parsec#27]
I would like to suggest implementing JSDoc/TSDoc so that when working with the framework you don't always have to look in the documentation but that some of this information is already in the code.

**Comment by ZihanChen-MSFT** [comment]
Thanks for your suggestion, but in my opinion, this library is not that easy to work by trying this and that, without reading the document. All you need to do is start by the sample, and learn **all** combinators. It is very important to learn **all** combinators before parse your text, so that you are able to write the most optimized parser for your syntax.

So I think I would just let all the information staying in the document for now.
